name: Play the game
on:
  issues:
    types: [opened]
jobs:
  playGame:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: get the target word
        run: |
          LINE=$(echo "$EVENT_ID % $(cat words.txt | wc -l) + 1" | bc)
          TARGET=$(head -n $LINE words.txt | tail -n -1)
          GUESS=$(echo $TITLE | cut -c 1-5)
          ./wordle.py "$TARGET" "$GUESS"
        env:
          EVENT_ID: ${{ github.event.issue.id }}
          TITLE: ${{ github.event.issue.title }}
